# Generated by Django 4.2.1 on 2023-05-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ig',
            options={'verbose_name_plural': 'IGs'},
        ),
    ]
